spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/maths
    username: labuser
    password: labpass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
